
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productModule
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: stockModule
          uri: lb://stock-service
          predicates:
            - Path=/stock/**
  main:
    web-application-type: reactive

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/