server:
  port: 8091

spring:
  application:
    name: stock-service
  zipkin:
    base-url: http://localhost:9411/
  main:
    allow-circular-references: true

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)