server:
  port: 9090

spring:
  application:
    name: ServiceOne
  zipkin:
    base-url: http://localhost:9411/
  main:
    allow-circular-references: true

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)
