server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

  instance:
    hostname: localhost
#https://stackoverflow.com/questions/59999740/feignclient-not-resolving-eureka-service-name

spring:
  application:
    name: stock-service