
server:
  port: 8901

eureka:
  client:
    defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ProductService

feign:
  client:
    config:
      default:
        connect-timeout: 160000000
        read-timeout: 160000000